COMMANDS = {
  #'Header H1 (Setext)' => 'This is an H1'"\n"'=============',
  #'Header H2 (Setext)' => 'This is an H2'"\n"'-------------',
  'Header H1' => '# This is an H1',
  'Header H2' => '## This is an H2',
  'Header H3' => '### This is an H3',
  'Header H4' => '#### This is an H4',
  'Header H5' => '##### This is an H5',
  'Header H6' => '###### This is an H6',
  'Blockquote' => '> This is a blockquote. Lorem ipsum dolor sit amet...',
  'Unordered list' => '-',
  'Unordered list ' => '*',
  'Unordered list (alt)' => '+',
  'Ordered list' => '1.',
  #'Code inline' => '`<code>`',
  'Code block' => '	(Tab)',
  'Horizontal line' => '* * *',
  'Horizontal line (alt)' => '---------------------------------------',
  'Bold' => '**Text**',
  'Bold (alt)' => '__Text__',
  'Italic' => '*Text*',
  'Italic (alt)' => '_Text_',
  #'Link' => '<http://example.com/>',
  'Link (Internal)' => '[Linktext](/page/)',
  #'Link (External URL)' => '[Linktext](http://example.com/ "Title text")',  
  #'Image' => '![Alt text](/path/to/img.jpg "Optional title")'
}